<?php
declare(strict_types=1);

return [
    ['id'=>'profile','type'=>'profile','slug'=>'profile','title'=>'Profile','sort_order'=>0,'is_published'=>1,'data'=>[
        'name'=>'Aimie Villabeto','full_name'=>'Aimie Villabeto D.','role'=>'Student Developer','location'=>'Regla, Guipos, Zamboanga del Sur','address'=>'Regla, Guipos, Zamboanga del Sur','availability'=>'Open to collaborations','age'=>'21','birthdate'=>'March 7, 2005','sex'=>'Female','school'=>'JH Cerilles State College','course_year'=>'Bachelor of Information Technology — 4th Year','dream_job'=>'Developer',
        'intro'=>'I am a student developer committed to improving my skills and building better solutions through consistent practice.','biography'=>'I continuously learn, explore new technologies, and strengthen how I design and develop practical systems. Every project and activity is an opportunity to grow, learn from challenges, and become a better developer.','skills'=>['HTML','CSS','PHP','JavaScript','MySQL','Python','Git','Flutter','Dart','REST APIs','Responsive Web Design','System Design']]],
    ['id'=>'system','type'=>'current_system','slug'=>'current-system','title'=>'Current System','sort_order'=>0,'is_published'=>1,'data'=>[
        'name'=>'Community Service Management System','summary'=>'A simple workspace for resident requests and staff review.','description'=>'The system organizes requests, document verification, status tracking, and reporting in one clear workflow.','status'=>'In development','progress'=>68,'technologies'=>['Native PHP','MySQL','JavaScript','Tailwind CSS'],'current_focus'=>'Improving document review and status tracking.','next_milestone'=>'Complete usability testing.']],
    ['id'=>'project-1','type'=>'project','slug'=>'service-hub','title'=>'Service Hub','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Service Hub','slug'=>'service-hub','summary'=>'A request-management portal for community services.','description'=>'Residents submit requests while staff review information and update progress through a straightforward workflow.','status'=>'In development','year'=>'2026','technologies'=>['Native PHP','MySQL','JavaScript'],'highlights'=>['Owner-managed content','Clear status tracking','Responsive pages']]],
    ['id'=>'activity-1','type'=>'activity','slug'=>'interface-prototyping','title'=>'Interface Prototyping Workshop','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Interface Prototyping Workshop','slug'=>'interface-prototyping','date'=>'2026-07-18','category'=>'Workshop','summary'=>'Converted a paper workflow into a simple prototype.','description'=>'I mapped each task, removed repeated steps, and tested a clearer interface.','outcomes'=>['Improved information hierarchy','Practiced workflow mapping','Recorded user feedback']]],
    ['id'=>'reflection-1','type'=>'reflection','slug'=>'designing-with-evidence','title'=>'Designing with Evidence','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Designing with Evidence','slug'=>'designing-with-evidence','date'=>'2026-07-20','course'=>'Systems Analysis and Design','instructor'=>'Sample Instructor','activity'=>'Interface Prototyping Workshop','experience'=>'I converted a multi-step workflow into an interactive prototype.','observations'=>'Users depended on familiar wording and visible progress.','learning'=>'I learned to test design decisions instead of treating them as final answers.','next_steps'=>'Test important workflows earlier and document each revision.','conclusion'=>'Useful systems grow through observation, iteration, and respect for users.']],
    ['id'=>'resume','type'=>'resume','slug'=>'resume','title'=>'Resume','sort_order'=>0,'is_published'=>1,'data'=>[
        'resume_version'=>2,'name'=>'AIMIE VILLABETO D.','headline'=>'STUDENT DEVELOPER','location'=>'Regla, Guipos, Zamboanga del Sur','phone'=>'','email'=>'','github'=>'github.com/aimievillabeto-dragon','linkedin'=>'','website'=>'Portfolio','summary'=>'Student developer committed to improving her skills and building practical solutions through consistent learning and hands-on work.','skills'=>[['group'=>'Languages','items'=>['PHP','JavaScript','Python','HTML','CSS']],['group'=>'Databases','items'=>['MySQL']],['group'=>'Tools & Platforms','items'=>['Git','GitHub','VS Code']]],'projects'=>[],'education_degree'=>'','education_period'=>'','education_school'=>'','activity_role'=>'','activity_organization'=>'','activity_year'=>'','activity_details'=>'','certifications'=>'']],
    ['id'=>'contact','type'=>'contact','slug'=>'contact','title'=>'Contact','sort_order'=>0,'is_published'=>1,'data'=>[
        'email'=>'','message'=>'View my work and projects on GitHub.','links'=>[['label'=>'GitHub','url'=>'https://github.com/aimievillabeto-dragon']]]],
];
