<?php
declare(strict_types=1);

return [
    ['id'=>'profile','type'=>'profile','slug'=>'profile','title'=>'Profile','sort_order'=>0,'is_published'=>1,'data'=>[
        'name'=>'Aimie Villabeto','full_name'=>'Aimie Villabeto D.','role'=>'Student Developer','location'=>'Regla, Guipos, Zamboanga del Sur','address'=>'Regla, Guipos, Zamboanga del Sur','availability'=>'Open to collaborations','age'=>'21','birthdate'=>'March 7, 2005','sex'=>'Female','school'=>'JH Cerilles State College','course_year'=>'Bachelor of Information Technology — 4th Year','dream_job'=>'Developer',
        'intro'=>'BS Information Technology Student at Josefina H. Cerilles State College. Passionate about Web Development, Database Management, and Cybersecurity.','biography'=>'I am passionate about web development and database management, where I enjoy creating functional and organized systems. I also have experience in developing capstone manuscripts and research documentation. Currently, I am exploring cybersecurity to expand my technical knowledge and better understand digital security practices.','skills'=>['HTML','CSS','PHP','JavaScript','MySQL','Python','Git','Flutter','Dart','REST APIs','Responsive Web Design','System Design']]],
    ['id'=>'system','type'=>'current_system','slug'=>'current-system','title'=>'Current System','sort_order'=>0,'is_published'=>1,'data'=>[
        'name'=>'Community Service Management System','summary'=>'A simple workspace for resident requests and staff review.','description'=>'The system organizes requests, document verification, status tracking, and reporting in one clear workflow.','status'=>'In development','progress'=>68,'technologies'=>['Native PHP','MySQL','JavaScript','Tailwind CSS'],'current_focus'=>'Improving document review and status tracking.','next_milestone'=>'Complete usability testing.']],
    ['id'=>'project-1','type'=>'project','slug'=>'service-hub','title'=>'Service Hub','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Service Hub','slug'=>'service-hub','summary'=>'A request-management portal for community services.','description'=>'Residents submit requests while staff review information and update progress through a straightforward workflow.','status'=>'In development','year'=>'2026','technologies'=>['Native PHP','MySQL','JavaScript'],'highlights'=>['Owner-managed content','Clear status tracking','Responsive pages']]],
    ['id'=>'activity-1','type'=>'activity','slug'=>'interface-prototyping','title'=>'Interface Prototyping Workshop','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Interface Prototyping Workshop','slug'=>'interface-prototyping','date'=>'2026-07-18','category'=>'Workshop','summary'=>'Converted a paper workflow into a simple prototype.','description'=>'I mapped each task, removed repeated steps, and tested a clearer interface.','outcomes'=>['Improved information hierarchy','Practiced workflow mapping','Recorded user feedback']]],
    ['id'=>'reflection-1','type'=>'reflection','slug'=>'becoming-a-professional-it-practitioner','title'=>'Becoming a Professional IT Practitioner','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Becoming a Professional IT Practitioner',
        'slug'=>'becoming-a-professional-it-practitioner',
        'date'=>'2026-08-22',
        'course'=>'Bachelor of Science in Information Technology',
        'instructor'=>'IT Department',
        'paragraphs'=>[
            'Professionalism in Information Technology means more than simply knowing how to use computers, develop software, or troubleshoot technical problems. For me, professionalism in IT means performing tasks responsibly, ethically, respectfully, and with integrity. As a BSIT student, I believe that professionalism involves not only having technical knowledge but also demonstrating good character and accountability in every task. Technical skills alone are not enough because IT professionals handle important information, computer systems, and digital resources that can affect individuals and organizations. Without professionalism, even a highly skilled IT professional can cause security issues, privacy violations, or damage to an organization\'s reputation.',
            'Among the characteristics of a professional IT practitioner, I believe my strongest quality is responsibility. As a student, I always try my best to complete assignments, participate in group activities, and submit projects on time. I understand the importance of being dependable because other people may rely on my work. However, I still need to improve my competence. Technology changes rapidly, and there are many areas in IT that I still need to learn, such as advanced programming, cybersecurity, cloud computing, and artificial intelligence. I recognize that becoming a competent IT professional requires continuous learning, practice, and dedication. Ethical responsibility is also an important part of professionalism. IT professionals often have access to sensitive information such as personal records, passwords, financial data, and confidential documents. Protecting confidentiality and respecting the privacy of others are essential because people trust IT professionals to handle their information responsibly. Unauthorized access or disclosure of information can lead to serious consequences, including identity theft, financial loss, and damage to personal or organizational trust. As a future IT professional, I understand that having access to information does not automatically give me the right to use or share it. Professional conduct can be demonstrated in many situations, even while I am still a student. For example, during a group project, I can show professionalism by communicating respectfully with my teammates, completing my assigned responsibilities, and helping solve problems when challenges arise. Instead of blaming others when mistakes occur, I should accept responsibility and work together to find solutions. This attitude helps create a positive and productive environment where everyone can contribute effectively.',
            'Cybersecurity responsibility is another important lesson I learned from the lecture. If I discovered that a classmate or coworker had written their password beside their computer, I would not use the password or ignore the situation. Instead, I would politely inform them that their password is exposed and explain the security risks involved. I would recommend using stronger password management practices and encourage them to change their password immediately. A professional IT practitioner should help protect systems and information rather than take advantage of security weaknesses. Digital professionalism is equally important in today\'s connected world. Social media posts, online communication, and digital behavior can significantly affect a person\'s reputation. Employers, clients, and colleagues may view online activities as reflections of an individual\'s character and professionalism. Because of this, I should be careful about what I post online, avoid offensive content, communicate respectfully, and maintain a positive digital presence. Responsible online behavior helps build credibility and trust, which are important qualities for future IT professionals. Continuous learning is necessary because technology continues to evolve rapidly. New programming languages, software tools, security threats, and technological innovations emerge every year. If IT professionals stop learning, their knowledge can quickly become outdated. For this reason, I plan to continue developing my skills even after graduation. In the future, I would like to learn more about cybersecurity, artificial intelligence, cloud computing, data analytics, and modern web development technologies. These areas are becoming increasingly important in the IT industry and can help me become a more versatile professional.',
            'As a future IT professional, I commit myself to continuously improving my technical skills through learning and practice, protecting confidential information and respecting the privacy of others, and demonstrating honesty, responsibility, and professionalism in all my academic and professional activities. I also commit to using technology ethically, maintaining respectful communication, and adapting to new technologies throughout my career. By following these commitments, I hope to become a competent, responsible, and trustworthy IT professional who contributes positively to society and the technology industry.'
        ]
    ]],
    ['id'=>'reflection-2','type'=>'reflection','slug'=>'understanding-ai-literacy-and-responsible-use','title'=>'Understanding AI Literacy and Responsible Use','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Understanding AI Literacy and Responsible Use',
        'slug'=>'understanding-ai-literacy-and-responsible-use',
        'date'=>'2026-09-19',
        'course'=>'Bachelor of Science in Information Technology',
        'instructor'=>'IT Department',
        'paragraphs'=>[
            'Taking the online course Introduction to AI Literacy and Responsible Use helped me understand that Artificial Intelligence (AI) is a broad field of computing that involves systems designed to perform tasks associated with human intelligence. I learned that AI does not necessarily think or understand the world like humans do, nor does it have human experiences or intentions. Generative AI can produce explanations, summaries, ideas, images, and code in seconds, but its output can still contain errors or misleading information. This taught me that AI is a useful tool for supporting human work and learning, but its output still requires human judgment and verification.',
            'The course also helped me understand the importance of proper prompting when using AI. I learned that effective prompts should provide a clear role, task, and context, along with relevant background information and specific goals. Instead of giving a vague instruction, I can explain exactly what I need, who the output is for, and how I want the response to be presented. I also learned that prompts can be improved through iteration. If the result is too general or does not meet my expectations, I can refine the instructions and provide additional details. At the same time, I need to check the information generated by AI because it can produce content that sounds correct but is actually false or unsupported, known as hallucination.',
            'Another lesson I gained is that AI literacy requires continuous learning and responsible use. The idea of Advanced and Accessible Lifelong Learning showed me that education should continue beyond completing a degree because technology, industries, and job requirements constantly change. As a learner, I need to continuously develop my skills and adapt to new technologies. Responsible use also means protecting sensitive information when using AI tools. Sharing personal, confidential, or organizational information with public AI systems may create privacy and security risks, so I should always consider what information is appropriate to provide.',
            'Overall, the course taught me that AI literacy is more than simply knowing how to use an AI tool. It involves understanding how AI works, communicating with it effectively, evaluating its output, protecting information, and knowing when human judgment is needed. I also learned the difference between automation, where AI performs tasks with limited human involvement, and augmentation, where AI assists people in completing tasks. For me, AI is most valuable when it enhances my abilities and learning rather than replacing my own effort and decision-making. This course encouraged me to become a more careful, critical, and responsible user of AI.'
        ]
    ]],
    ['id'=>'resume','type'=>'resume','slug'=>'resume','title'=>'Resume','sort_order'=>0,'is_published'=>1,'data'=>[
        'resume_version'=>2,'name'=>'AIMIE VILLABETO D.','headline'=>'STUDENT DEVELOPER','location'=>'Regla, Guipos, Zamboanga del Sur','phone'=>'','email'=>'','github'=>'github.com/aimievillabeto-dragon','linkedin'=>'','website'=>'Portfolio','summary'=>'Student developer committed to improving her skills and building practical solutions through consistent learning and hands-on work.','skills'=>[['group'=>'Languages','items'=>['PHP','JavaScript','Python','HTML','CSS']],['group'=>'Databases','items'=>['MySQL']],['group'=>'Tools & Platforms','items'=>['Git','GitHub','VS Code']]],'projects'=>[],'education_degree'=>'','education_period'=>'','education_school'=>'','activity_role'=>'','activity_organization'=>'','activity_year'=>'','activity_details'=>'','certifications'=>'']],
    ['id'=>'contact','type'=>'contact','slug'=>'contact','title'=>'Contact','sort_order'=>0,'is_published'=>1,'data'=>[
        'email'=>'','message'=>'View my work and projects on Facebook and GitHub.','links'=>[
            ['label'=>'Facebook','url'=>'https://www.facebook.com/share/1CovpVL5Yy/'],
            ['label'=>'GitHub','url'=>'https://github.com/aimievillabeto-dragon']
        ]]],
];
